### ISSUE TITLE
I can't open the "https://code.jquery.com/jquery-3.3.1.min.js" in my country,this caused many problems.

### ISSUE THREAD

**Issue by Zahichoy** [riflowth/SkinSystem#101]
Hello,I am a chinese user.And i found that the install page can't work properly.The check box of authme dosen't work at all.After checking,i change the source of the file"jquery.min.js",the problem was solved.

BUT，after installing,I can't open my site.It opens very slowly,and prints the html code directly.I checked the index.php page,and i found that you have encode something,I try to delete them,and re reference javascprit part,it can open easily.

BUT, The preview skin part can't work. I am not a professional user,HOW can i solve this problem? I sincerely hope you can offer me some help.Thanks for your kindness.

**Comment by Zahichoy** [comment]
And,I have changed my Authme database table name,how can i match authme to my site?

**Comment by riflowth** [comment]
> And,I have changed my Authme database table name,how can i match authme to my site?

Edit **config.nogit.php** to match your authme configuration.

**Comment by riflowth** [comment]
> The preview skin part can't work

Does it have an error in your log? I think some JS library has blocked.

**Comment by Zahichoy** [comment]
This is my site: skin.iecraft.com . Every funtions works well ,except for the preview part.I can open these links,but i don't know whether i edit the index.php properly,whether my site reference these libs.
