### ISSUE TITLE
error wordpress connecting

### ISSUE THREAD

**Issue by VladDollar** [riflowth/SkinSystem#103]
Hello! I'm trying to connect SkinSystem to my "Wordpress-AuthMe" inegration auth setup. General problem (I think) is custom  database names in AuthMeReloaded config. Because it's working excellent without AuthMe verification. 

So, first of all, my AuthMe config 

https://pastebin.com/d7tchaei
pass:kDmFcjG8yp

And my auto generated config.nogit.php:

https://pastebin.com/h0KL0VYV
pass:DTkiwTz3Zc

I have searched in SkinSystem code, that I can change custom database fields names can be changed in authenCore.php. 
So, I modified it, but this still not working :(        (line 36):

https://pastebin.com/QExe1BXr
pass:yQwPmCt2bv

The error is: incorrect username or password, so i don't know, what is the problem in, i even tried to change hash, but this not working.

Please, help

**Comment by riflowth** [comment]
You forget to change **line 38**

```php
if(isValidPassword($password, $pdo->fetch(PDO::FETCH_ASSOC)['password'])){
```

to

```php
if(isValidPassword($password, $pdo->fetch(PDO::FETCH_ASSOC)['user_pass'])){
```

**Comment by VladDollar** [comment]
I tried this, but still Incorrect Username or Password. Im not good at PHP, so i think the problem is very likely im my "modifications", but these are just 2 lines :). So, maybe somewhere else i should change fields to custom?

**Comment by VladDollar** [comment]
Finally, I understood what is the problem in. My Hash algorythm is wordpress, but authenCore.php doesn't support it. So, plz would you help me this hash type to 'function isValidPassword'

**Comment by VladDollar** [comment]
Yes! I finally found a solution, sorry to worried you :)

**Comment by chelminski** [comment]
Can you share the solution?
