### ISSUE TITLE
Wordpress Authentication

### ISSUE THREAD

**Issue by chelminski** [riflowth/SkinSystem#104]
Hello! I have wordpress page (The authme database is the same for the site and the server). Players have a panel on the site where they can buy ranks, change the password (the server is non-premium), etc. Could I ask you to create a simple wordpress plugin that would automatically enter the nickname of the currently logged in user?

**Comment by riflowth** [comment]
The SkinSystem doesn't support **wordpress** if you want to use with **wordpress** you can modify the sourcecode on `resources/server/authenCore.php` for authentication.
