### ISSUE TITLE
Feature Request: API For Developers

### ISSUE THREAD

**Issue by FireHead90544** [riflowth/SkinSystem#111]
[Feature Request] - API For Developers

Please do create a REST API, from which people can provide a link to their skin and name of the skin and the web server will return the skin file as a file/link format.

I am sorry, I would have created the API myself, but I am only comfortable with python, which is not used here 😅

**Comment by riflowth** [comment]
You can directly use [**MineSkin API**](https://github.com/MineSkin/api.mineskin.org) to get skin texture and signature
