### ISSUE TITLE
webpage stuck on white after instalation 

### ISSUE THREAD

**Issue by VozDeOuro** [riflowth/SkinSystem#113]
my webpage in Nginx don't load after a complete instalation 

![image](https://user-images.githubusercontent.com/36045463/115949603-9836f200-a4ac-11eb-9bed-6c9bd1e8cc7b.png)

**Comment by riflowth** [comment]
Show your Nginx error logs please, we can't help you without any error information.

**Comment by VozDeOuro** [comment]
sorry i forgot 
https://pastebin.com/vauvRFkt

**Comment by riflowth** [comment]
```
PHP message: sessionserver.mojang.com is having issues
```
Try again later, after Mojang API working properly
