### ISSUE TITLE
please use classes and not pdo for databases

### ISSUE THREAD

**Issue by writeescape** [riflowth/SkinSystem#18]
Having read your php code I think you'ld be better off using and implementing this:
[https://github.com/ThingEngineer/PHP-MySQLi-Database-Class/](url) 

if you need help updating your php code let me know and i'll help you

**Comment by riflowth** [comment]
Sorry, I think PDO is better than MySQLi and more easier. (Why?)

**Comment by writeescape** [comment]
it has more functions for your purpose and makes it look easier to read

**Comment by riflowth** [comment]
https://www.phpclasses.org/blog/post/521-mysqli-vs-pdo-vs-mysql.html

**Comment by writeescape** [comment]
read the class i linked you, pdo isn't widely supported in the field thesedays

**Comment by riflowth** [comment]
PDO is flexible and able to work with multiple database systems and more security than MySQLi.

**Comment by riflowth** [comment]
https://stackoverflow.com/questions/13569/mysqli-or-pdo-what-are-the-pros-and-cons

https://stackoverflow.com/questions/24459214/preventing-sql-injection-with-pdo-or-mysqli
