### ISSUE TITLE
PDO failed to parse address localhost:3306:3306

### ISSUE THREAD

**Issue by lion328** [riflowth/SkinSystem#21]
During the final step of installation, PDO can't connect to database. In `ajax.php`:

```php
new PDO("mysql:host=localhost:3306;dbname=...")
```

Causing `PDOException: SQLSTATE[HY000] [2002] Failed to parse address "localhost:3306:3306"`

This can be fixed by specific port in `port` parameter like this:

```php
new PDO("mysql:host=localhost;port=3306;dbname=...")
```

PHP Version 7.0.18-0ubuntu0.16.04.1

**Comment by LazosPlaying** [comment]
@lion328 can you send me the paste of your /lib/config.nogit.php (don't forget to replace the password, address, username, dbname)
