### ISSUE TITLE
Cannot login. 

### ISSUE THREAD

**Issue by HimikoEmu** [riflowth/SkinSystem#24]
It says that it failed to connect to the server.

**Comment by LazosPlaying** [comment]
Then re-edit the file `/lib/config.nogit.php` and insert the correct MySql credentials. Also make sure that the database is accessible from remote locations (in case you are running your database on a remote server)

**Comment by riflowth** [comment]
@lazosplaying Thanks for help me replying. 👍🏻

**Comment by HimikoEmu** [comment]
I am sure everything is correct. I am a SQL developer myself so it would be a shame if I misconfigured it. Will check later. Thanks for replying!

**Comment by riflowth** [comment]
@HimikoEmu When you finish installation of the SkinSystem anything print with a green text ?

**Comment by riflowth** [comment]
Oh, Can you send me your website that install the SkinSystem sometime error by a path?
