### ISSUE TITLE
All settings are correctly provided, however the setup fails at "Check data and Finish".

### ISSUE THREAD

**Issue by Xeddius** [riflowth/SkinSystem#27]
I have SkinRestorer setup and connected to MySQL all of the settings are correct and working perfectly.
SkinSystem however has been a thorn in my side as no matter what I do, even with every setting quadruple checked and verifed as correct I receive the error below:
`  { "[error]": "Not all variables were correctly provided", "[info]": "Please recheck every input field and make sure it is corrctly filled in." }`

I am 100% certain every single value is as it should be.

**Comment by riflowth** [comment]
Check your last page of installation which fields that you don’t fill it. Make sure all fields are entered correctly.

**Comment by riflowth** [comment]
So the problem is on the code of authme. I going to fix it, Thanks 😀

**Comment by Xeddius** [comment]
No error is shown, however after clicking the check and finish button it greys out and then freezes indefinitely, I've waited over 15 minutes and it has not changed, reloaded, updated, etc. Returning to localhost/index.php takes me back to the beginning of setup.

TL:DR Setup never finishes.

**Comment by riflowth** [comment]
What's the problem now?

**Comment by Xeddius** [comment]
"Setup never finishes." There's no error log, it just never completes the setup.

**Comment by riflowth** [comment]
Can you take a screenshot for me please?

**Comment by riflowth** [comment]
New Version with new installation system : https://github.com/riflowth/SkinSystem/tree/1.6 👍
