### ISSUE TITLE
Not connected to the authme database

### ISSUE THREAD

**Issue by bot4you** [riflowth/SkinSystem#30]
When I want to log in with authme, he writes: I could not connect to the server. Here's a picture of it.
![kepkivagas](https://user-images.githubusercontent.com/46109529/51332824-bebf8480-1a7c-11e9-8188-422975be8c37.PNG)

**Comment by riflowth** [comment]
Please re-check your Authme configuration. Does the database configuration is correct?

**Comment by riflowth** [comment]
And please don't change a current version in your configuration.

**Comment by bot4you** [comment]
Here is my configuration

<?php
/*
	Skin-System
	https://github.com/riflowth/SkinSystem
*/
 
	return [
		'authme' => array(
			/* Authme Configuration */
			'enabled' => true,
			'host' => 'mysql.nethely.hu',
			'port' => '3306',
			'username' => 'authme',
			'password' => 'valid pw',
			'database' => 'authme',
			'table' => 'authme'
		),
		'sr' => array(
			/* SkinsRestorer Configuration */
			'host' => 'mysql.nethely.hu',
			'port' => '3306',
			'username' => 'skin',
			'password' => 'valid pw',
			'database' => 'skin',
			'tbl_skins' => 'Skins',
			'tbl_players' => 'Players'
		),
		'sys' => array(
			/* SkinSystem Configuration */
			'name' => 'PlayClan',
			'skinhistory' => true,
			'is_public' => false,
			'new_version_notify' => true,
			/* Do-not-touch part */
			'version' => '1.0',
			/* First-load install system */
			'is_installed' => true
		)
	];
?>

**Comment by bot4you** [comment]
> <?php
/*
	Skin-System
	https://github.com/riflowth/SkinSystem
*/
 
	return [
		'authme' => array(
			/* Authme Configuration */
			'enabled' => true,
			'host' => 'mysql.nethely.hu',
			'port' => '3306',
			'username' => 'authme',
			'password' => 'PlayClans123',
			'database' => 'authme',
			'table' => 'authme'
		),
		'sr' => array(
			/* SkinsRestorer Configuration */
			'host' => 'mysql.nethely.hu',
			'port' => '3306',
			'username' => 'skin',
			'password' => 'PlayClans123',
			'database' => 'skin',
			'tbl_skins' => 'Skins',
			'tbl_players' => 'Players'
		),
		'sys' => array(
			/* SkinSystem Configuration */
			'name' => 'PlayClan',
			'skinhistory' => true,
			'is_public' => false,
			'new_version_notify' => true,
			/* Do-not-touch part */
			'version' => '1.5',
			/* First-load install system */
			'is_installed' => true
		)
	];
?>

**Comment by bot4you** [comment]
> <?php
/*
	Skin-System
	https://github.com/riflowth/SkinSystem
*/
 
	return [
		'authme' => array(
			/* Authme Configuration */
			'enabled' => true,
			'host' => 'mysql.nethely.hu',
			'port' => '3306',
			'username' => 'authme',
			'password' => 'cheesy',
			'database' => 'authme',
			'table' => 'authme'
		),
		'sr' => array(
			/* SkinsRestorer Configuration */
			'host' => 'mysql.nethely.hu',
			'port' => '3306',
			'username' => 'skin',
			'password' => 'cheesy',
			'database' => 'skin',
			'tbl_skins' => 'Skins',
			'tbl_players' => 'Players'
		),
		'sys' => array(
			/* SkinSystem Configuration */
			'name' => 'PlayClan',
			'skinhistory' => true,
			'is_public' => false,
			'new_version_notify' => true,
			/* Do-not-touch part */
			'version' => '1.5',
			/* First-load install system */
			'is_installed' => true
		)
	];
?>

**Comment by riflowth** [comment]
I think the problem depend on your connection between your database server and webserver.
