### ISSUE TITLE
 Error when I set skins for player

### ISSUE THREAD

**Issue by forkzch** [riflowth/SkinSystem#35]
Not all skins work, i see "Please re-upload or contact WebMaster!"
![ppMDJ-ydmZ0](https://user-images.githubusercontent.com/48773257/54718482-b0204700-4b6b-11e9-9a33-0bf29a6e5776.jpg)
![m-MFs3EKbVM](https://user-images.githubusercontent.com/48773257/54718487-b282a100-4b6b-11e9-94a3-7f69569a1e31.jpg)

**Comment by forkzch** [comment]
add* Sometimes skin is installed, 50/50 wtf russian roulette

**Comment by forkzch** [comment]
ama test 64x64 and 64x32 skins, but 80% not working

**Comment by riflowth** [comment]
Can you send me some skin that give you an error?

**Comment by forkzch** [comment]
[skins.zip](https://github.com/riflowth/SkinSystem/files/2990823/skins.zip) a lot of skins from sites don't work..

**Comment by forkzch** [comment]
some skins are loaded from 3-5 attempts

**Comment by forkzch** [comment]
https://elysi.fun/skins/ login: test pass: 12345d

**Comment by forkzch** [comment]
![image](https://user-images.githubusercontent.com/48773257/54734153-bd125a00-4bae-11e9-8d4a-82abb8d31073.png)
u set skin, it works

**Comment by riflowth** [comment]
I have checked it now, the API endpoint is down

**Comment by forkzch** [comment]
when fix?

**Comment by forkzch** [comment]
u'r very fast, thanks
