### ISSUE TITLE
Having trouble installing.

### ISSUE THREAD

**Issue by ITZVGcGPmO** [riflowth/SkinSystem#36]
using apache2, on ubuntu with php addons installed.

1.6 release sends me back to a blank page after installation, config.nogit.php has malparsed parameters.

1.5 seems to work well, but spits out 
```
{ "[success]": "Test for all provided variables succeeded" }

{ "Testing skinsrestorer MySql:": false, "[error]": { "errorInfo": null } }

{ "[error]": { "errorInfo": null } }

{ "[success]": "The /lib directory has valid permissions" }

{ "[error]": "Something is not okay.", "[info]": "Quitting installation proccess..." }
```
once "Check data and finish" is chosen.

**Comment by riflowth** [comment]
Have you added **chmod 775** in your skinsystem directory ??

**Comment by riflowth** [comment]
Can you send me a config.nogit.php that you said "malparsed parameters" ??

**Comment by ITZVGcGPmO** [comment]
[AuthMe.yml](https://gist.github.com/ITZVGcGPmO/48fd8568d6e9627be11a36be2a6b8fb3/raw/2981ae7f78bb68ec5259de41e13edd818f8700cb/AuthMe.yml)
[config.nogit.php](https://gist.github.com/ITZVGcGPmO/48fd8568d6e9627be11a36be2a6b8fb3/raw/2981ae7f78bb68ec5259de41e13edd818f8700cb/config.nogit.php)
[SkinsRestorer.yml](https://gist.github.com/ITZVGcGPmO/48fd8568d6e9627be11a36be2a6b8fb3/raw/2981ae7f78bb68ec5259de41e13edd818f8700cb/SkinsRestorer.yml)

same results after doing both `chown -R www-data:www-data html` and `chmod -R 775 html` after placing the contents of the `skinsystem` folder into the default `html` dir of apache2

**Comment by riflowth** [comment]
Try to edit **config.nogit.php** by yourself.

**Comment by riflowth** [comment]
```php
<?php
    return [
        'version' => 1.6,
        /* SkinsRestorer Configuration */
        'sr' => [
            'host' => 'localhost',
            'port' => '3306',
            'database' => 'skinsrestorerUsername',
            'skintable' => 'Skins',
            'playretable' => 'Players',
            'username' => 'user',
            'password' => 'passwordSkinTable'
        ],
        /* Authme Configuration */
        'authme' => [
            'enabled' => true,
            'host' => '127.0.0.1',
            'port' => '3306',
            'database' => 'authme',
            'username' => 'user',
            'password' => 'password'
        ]
    ];
?>
``` Something like this 😄

**Comment by ITZVGcGPmO** [comment]
this should be correct formatting, yet the web page still is blank?
```
<?php
    return [
        'version' => 1.6,
        /* SkinsRestorer Configuration */
        'sr' => [
            'host' => 'localhost',
            'port' => '3306',
            'database' => 'skinsrestorer',
            'skintable' => 'Skins',
            'playretable' => 'Players',
            'username' => 'user',
            'password' => 'password'
        ],
        /* Authme Configuration */
        'authme' => [
            'enabled' => true,
            'host' => '127.0.0.1',
            'port' => '3306',
            'database' => 'authme',
            'username' => 'user',
            'password' => 'password'
        ]
    ];
?>
```
the html i get back from the web server is `<html><head></head><body></body></html>`, a blank page

**Comment by riflowth** [comment]
Correct!, Check your url does it correct????

**Comment by ITZVGcGPmO** [comment]
the response i get from the apache2 server is 
```html
<html><head></head><body></body></html>
```
when my web browser requests the root page

**Comment by ITZVGcGPmO** [comment]
(I assume it's supposed to serve more content, right?)

**Comment by riflowth** [comment]
I am checking something please wait 😄

**Comment by ITZVGcGPmO** [comment]
I'll be a little more specific on my environment for sake of issue reprocution: 
```
Ubuntu 18.04.2 LTS Server
Apache2: 2.4.29
apt addon package: libapache2-mod-php7.2
```

**Comment by aljaxus** [comment]
Also, did this issue with 1.6 occur when you used the config importer?

**Comment by ITZVGcGPmO** [comment]
the malparsed config and "empty" webpage happens on 1.6, version 1.5 shows [some errors](https://github.com/riflowth/SkinSystem/issues/36#issue-424721210)

**Comment by ITZVGcGPmO** [comment]
this seems to be the main error in apache's error.log
```php
[php7:error] [client <ip:port>] PHP Fatal error:  Uncaught PDOException: could not find driver in /var/www/html/resources/server/libraries.php:7\nStack trace:\n#0 /var/www/html/resources/server/libraries.php(7): PDO->__construct('mysql:host=127....', 'user', 'password')\n#1 /var/www/html/index.php(4): require_once('/var/www/html/r...')\n#2 {main}\n  thrown in /var/www/html/resources/server/libraries.php on line 7
```

**Comment by ITZVGcGPmO** [comment]
I am quite stupid. Didn't install `php7.2-curl` and `php7.2-mysql` to go along with `libapache2-mod-php7.2` and `apache2`

**Comment by riflowth** [comment]
Oh, Thank you. Now I need to care about libraries that users use. And you should use new version of SkinSystem. :smile:
