### ISSUE TITLE
"Slimness" of skins cannot be changed

### ISSUE THREAD

**Issue by ITZVGcGPmO** [riflowth/SkinSystem#39]
I cannot seem to upload a skin marked as slim, and have it show up as slim in skinsrestorer

**Comment by riflowth** [comment]
Have you tried to re-upload the skin?

**Comment by ITZVGcGPmO** [comment]
apparently the skin has to be modified to change it's slimness. once the skin has been uploaded, the slimness cannot be changed.

**Comment by ITZVGcGPmO** [comment]
https://github.com/MineSkin/api.mineskin.org/issues/29

**Comment by ITZVGcGPmO** [comment]
It seems as if the mineskin uploader handles this by marking it as a steve skin, even though it is an alex model.

**Comment by ITZVGcGPmO** [comment]
seems to be fixed by the mineskin api in the meantime.
