### ISSUE TITLE
Generate skin

### ISSUE THREAD

**Issue by brutalzinn** [riflowth/SkinSystem#40]
How do I generate skins for my users? generate the current skin when they enter the panel ...?

**Comment by riflowth** [comment]
The SkinSystem isn't for generate skin. You should use https://github.com/riflowth/SkinFile-Generator for geneate a skin for your users. (The SkinSystem developed for cracked Minecraft's server allowing to change their player skin into a custom skin.)

**Comment by brutalzinn** [comment]
I do not think you understood my question. I'm referring to the panel, where the skin is uploaded. On the right side there is a viewer that only works after selecting the skin. I would like it to show the user's current skin as soon as it enters the page ..

**Comment by riflowth** [comment]
You can edit the soucrecode to add this feature by yourself. If you need help leave your question here.

**Comment by ITZVGcGPmO** [comment]
@brutalzinn this feature was implemented in the sauce code as of pull #37
