### ISSUE TITLE
[Bug] Cant disabled  authsec

### ISSUE THREAD

**Issue by maxlehot1234** [riflowth/SkinSystem#47]
Hey, I cant disabled the authsec to test the website.

Also, I can't "login" on the website, it simply wont let me login.
I use my MC username and my authme password.

Any reason for this?

Thanks again

**Comment by riflowth** [comment]
@maxlehot1234 What version are you use? and Have you try to manually edit your config file?

**Comment by maxlehot1234** [comment]
Yes I try to manually edit the config file. Take like an hour to allow me to login..

It works now :)

But doesn't work in-game because skinsrestorer plugin doesn't for me :(
Seems to be hard to found the problem :P

**Comment by riflowth** [comment]
Try to report an issue on https://github.com/SkinsRestorer/SkinsRestorerX. 😀👍

**Comment by maxlehot1234** [comment]
> Try to report an issue on https://github.com/SkinsRestorer/SkinsRestorerX. 😀👍

Dont worry about this. I open a ticket on their discord and they answer, but seems to be really hard to found the issue XD even for them :P

**Comment by riflowth** [comment]
@maxlehot1234 OK... Can I ask you for improving this system? What section do you have change in a config file? (I think it a mistake of installation system.)

**Comment by maxlehot1234** [comment]
I firstly change:

    'authsec' => [
      'enabled' => false,
      'failed_attempts' => 99,
      'threshold_hours' => 24
The failed attemps and try to increase it. Change nothing.
So I try to disable authsec, Change Nothing, need to wait a long time.

Not a big deal, but hard to test things when this occured ;)

**Comment by ITZVGcGPmO** [comment]
login ratelimits are stored in the cache directory, so if you clear the cache it should fix your issue.

**Comment by riflowth** [comment]
Thanks to @ITZVGcGPmO for patching this bug. @maxlehot1234 Now it should fix your issue. 👍
