### ISSUE TITLE
Error in UbuntuInstall.sh

### ISSUE THREAD

**Issue by RealCorebb** [riflowth/SkinSystem#53]
Line 8   it should be:cd SkinSystem
NOT cd SkinSytem

**Comment by ITZVGcGPmO** [comment]
thank you for ubmitting thi isue, my keyboard ometimes misse the `s` key. :laughing:

**Comment by aljaxus** [comment]
We can clearly see that in your reply :stuck_out_tongue: 
"isue"

> thank you for ubmitting thi isue, my keyboard ometimes misse the `s` key.

**Comment by ITZVGcGPmO** [comment]
I wear that I haven't done thi on purpoe.

**Comment by riflowth** [comment]
**Hank ou ery uch!** 😆
