### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by arturek1666** [riflowth/SkinSystem#55]
When try to install it say:
 Please make sure SkinsRestorerDB system is enabled!:
It's enabled tho

 Using:
1.14.2 paperspigot
Skinrestorer build: Build #88 (11-Jun-2019 14:10:06)

**Comment by riflowth** [comment]
What version of Skinsystem do you use?

**Comment by arturek1666** [comment]
Yes I use the latests

**Comment by riflowth** [comment]
Can you check configuration file? Does it correct?

**Comment by arturek1666** [comment]
I am on installation page while this message popsup. With configuration file?

**Comment by arturek1666** [comment]
Ok looks like when created skinrestorer config from scratch I made it

**Comment by ajgeiss0702** [comment]
What was the solution to this?

**Comment by arturek1666** [comment]
Fixing up the config resolved the issue :).

**Comment by ITZVGcGPmO** [comment]
#71
