### ISSUE TITLE
[FEATURE REQUEST] configurable AuthMe table names

### ISSUE THREAD

**Issue by Alperenn** [riflowth/SkinSystem#61]
#### Current behaviour:
Table names used for AuthMe MySql database are hardcoded and can not be moified until messing with source code

#### Suggested behaviour:
Table names for AuthMe MySql database are configurable in in installation menu.

**Comment by DrkMatr1984** [comment]
Would love this! I am trying to create an integrated phpbb, authme, skinsystem user database and this is preventing my dream from becoming a reality! :)

**Comment by riflowth** [comment]
Added on bd3e14f
