### ISSUE TITLE
"Cannot connect to the server!!!"

### ISSUE THREAD

**Issue by Andersson799** [riflowth/SkinSystem#62]
So i've been stuck on this step for so long, i tried changing the usernames, database names, nothing worked. I just configured everything up (spigot 1.14.4 with skinrestorer plugin, enabled database from config.yml file, open all ports, created database called "skinsrestorer",).
I'm currently using Windows Server 2012 R2 with xampp 7.3.7

What could be the problem?
![skinsystem](https://user-images.githubusercontent.com/16568983/62671674-fc0c4500-b9c1-11e9-9cbf-3bdff05f1a10.jpg)

**Comment by riflowth** [comment]
Try to download from lastest branch.

**Comment by ITZVGcGPmO** [comment]
^ in reference to commit https://github.com/riflowth/SkinSystem/commit/194768b72a12439f1b3f2ea334f67df706808ea2
