### ISSUE TITLE
Need help with installing

### ISSUE THREAD

**Issue by lolraceHun** [riflowth/SkinSystem#63]
![Screenshot_17](https://user-images.githubusercontent.com/40703369/62786777-97d1aa00-bac3-11e9-9d7e-6251001bd060.png)

-  I am using the latest skinrestorer
-  I am using the latest authmereloded
-  mysql is working
-  skinrestorer and authme connected to mysql 
-  tried latest version same error

**Comment by riflowth** [comment]
I have tried your config but It works. Do you download SkinSystem on master branch?

**Comment by riflowth** [comment]
**This issue has conversations on SkinsRestorer ticket!**
