### ISSUE TITLE
[Installation Issue] Enable SkinsRestorerDB in SkinsRestorer config!

### ISSUE THREAD

**Issue by Ayuei** [riflowth/SkinSystem#69]
I'm getting the **Enable SkinsRestorerDB in SkinRestorer config** message when I upload the config.yml for SkinRestorer. 

I can access the website and the sql database seem to be all created and the user can log in with `mysql -u root -p`.

I used the script provided for ubuntu 18+ distributions to handle the installation.

My config.yml file is here (root password removed): https://pastebin.com/1kfuQLTJ
Any ideas?

I'm using skinrestorer v 13.7.3 (spigot; minecraft v1.14), oddly the config generated appears to be for 13.7.2.

**Comment by ajgeiss0702** [comment]
I am having the same issue

**Comment by ajgeiss0702** [comment]
I seemed to have fixed it by configuring the values manually by editing config.nogit.php.example, then renaming it to config.nogit.php

Try this and see if it works.

**Comment by Ayuei** [comment]
This fixed it for me too! 

If anyone else has this issue:
1. Manually clone the repo contents and place this in your html folder.
2. Edit config.nogit.php.example with the correct mysql details.
3. Save as config.nogit.php.

**Comment by ITZVGcGPmO** [comment]
#71

**Comment by ITZVGcGPmO** [comment]
#77
