### ISSUE TITLE
Blank page by trying to install

### ISSUE THREAD

**Issue by IsRealMe** [riflowth/SkinSystem#74]
Hello, so I was trying to install this skin changer, but it won't work for me. Getting blank page on /SkinSystem-master/installation/?v=1.7.2
Php version I've got 7.2.23
mysql: Ver 14.14 Distrib 5.5.62, for Linux (x86_64) using readline 5.1
OS: CentOS-6(64bit)
I've got installed also apache2, php-curl, php-gd modules.

Old versions works fine.

**Comment by riflowth** [comment]
Can you give me your apache **error log**?

**Comment by Varo95** [comment]
Try change reading permissions or executable permisions on files

**Comment by riflowth** [comment]
@IsRealMe Does it work now?

**Comment by IsRealMe** [comment]
> @IsRealMe Does it work now?

Sorry for abandoning this post, I've used older version and that one worked, still using that older one.

**Comment by riflowth** [comment]
You can try it on the **latest master branch** *it has fixed many issues.*

**Comment by IsRealMe** [comment]
> You can try it on the **latest master branch** _it has fixed many issues._

Installed latest, works fine. Thanks!
