### ISSUE TITLE
[User Guide] AuthMe with PostgreSQL

### ISSUE THREAD

**Issue by scorninpc** [riflowth/SkinSystem#75]
First of all, thank you alot for this great tool

If you have a AuthMe with PostgreSQL (who is better if you cannot manage your MySQL server and use hosting database), you can change the PDO driver of index am to pgsql.

you stil need to use mysql for skinrestorer, but they can recriate a session when server drop the connection, what authme cannot

So you can use Postgresql for auth and mysql for skins, both from hosting services

So, you can change mysql to pgsql here https://github.com/riflowth/SkinSystem/blob/master/resources/server/libraries.php#L16

And remove / comment this line safetly https://github.com/riflowth/SkinSystem/blob/master/installation/installation.php#L100

Again, thank you for this nice job

**Comment by riflowth** [comment]
@scorninpc Thank you for this *documentation*
