### ISSUE TITLE
The notifications about mysql configuration

### ISSUE THREAD

**Issue by 623059008** [riflowth/SkinSystem#77]
In installation page, I got the notification after submiting my config.yml file.
![p1](https://i.loli.net/2019/12/14/PRerjlxpOUTWSBV.jpg)
I have no idea whether what I did is correct or not.
I use docker to deploy my paper spigot server and I move the SkinsRestorer.jar to plugins folder.
It works for me and I can use skins in game.
Then I stop docker server and download the config.yml for editing it, I submit the downloaded config file with my config.
![p2](https://i.loli.net/2019/12/14/QUcZGYIv5SJ1K7e.png)

And the notification shows up.

Any thoughts?
Thanks.

**Comment by ITZVGcGPmO** [comment]
we've seen some of this strangeness before; don't exactly know what the cause is. what is your php version?

**Comment by 623059008** [comment]
I run 'php -v' and get this.

PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by leol-js** [comment]
I have the same problem. I can attach any images if you need

**Comment by mecanosfera** [comment]
Same problem here, using php 7.2.24, on Ubuntu 18.04. 

The problem appears to be something related with the regex on line 81 of the installation.php file. Testing here, it catches the "MySQL:" line, but the other ones come empty, so it can't load any configuration data about the database. Testing in online regex editors the expressions works fine, but running the installation script doesn't. Could it have something to do with PHP 7? Looks like they are more strict about regex now.

**Comment by simonchow96** [comment]
Hi! I have modified the script installation.php a bit and it works! I have already created a pull request  and wait for admin's approval. Mealwhile you have have a look here: https://github.com/riflowth/SkinSystem/pull/80

**Comment by ITZVGcGPmO** [comment]
@623059008 hopefully your patch works; thank you :D
