### ISSUE TITLE
 Enable SkinsRestorerDB in SkinsRestorer config!

### ISSUE THREAD

**Issue by Mitsu13Ion** [riflowth/SkinSystem#78]
Hello, i have this error
Enable SkinsRestorerDB in SkinsRestorer config!
MySQL:
  Enabled: true
  Host: ////
  Port: ////
  Database: ////
  Username: ////
  Password: ////
  SkinTable: 'Skins'
  PlayerTable: 'Players'

**Comment by ITZVGcGPmO** [comment]
duplicate of #77
