### ISSUE TITLE
SALTED2MD5 implementation

### ISSUE THREAD

**Issue by nozombieWK** [riflowth/SkinSystem#84]
Windows 2016 x64
Apache2.4 x64 PHP5
Once I clicked on login button, there's no any responce, and I pressed F12 and check Console here, there writes "[ERROR] AJAX FAILED!".
Is there any solution?

**Comment by riflowth** [comment]
Please use *LATEST VERSION* of **SkinSystem**.
**if you use the latest version then please show me some error information.**
*(Apache error log / F12 Network menu)*

**Comment by nozombieWK** [comment]
well, I've already worked the problem out.
The main cause is that I used SALTED2MD5 encryption method which our SkinSystem doesn't support.
I've modified authenCore.php and just added SALTED2MD5 support, and that's it.
[authenCore.php.txt](https://github.com/riflowth/SkinSystem/files/4469080/authenCore.php.txt)

**Comment by riflowth** [comment]
Pull Request please! **nice work!**

**Comment by shinrariel-beichi** [comment]
> well, I've already worked the problem out.
> The main cause is that I used SALTED2MD5 encryption method which our SkinSystem doesn't support.
> I've modified authenCore.php and just added SALTED2MD5 support, and that's it.
> [authenCore.php.txt](https://github.com/riflowth/SkinSystem/files/4469080/authenCore.php.txt)

...if he dant know how to make a pull request?

**Comment by shinrariel-beichi** [comment]
> well, I've already worked the problem out.
> The main cause is that I used SALTED2MD5 encryption method which our SkinSystem doesn't support.
> I've modified authenCore.php and just added SALTED2MD5 support, and that's it.
> [authenCore.php.txt](https://github.com/riflowth/SkinSystem/files/4469080/authenCore.php.txt)

...if he dont know how to make a pull request?

**Comment by riflowth** [comment]
@shinrariel-beichi LOL, Why not!

**Comment by shinrariel-beichi** [comment]
> @shinrariel-beichi LOL, Why not!

...maybe a newbie?any pro won't upload his file here at all.

**Comment by riflowth** [comment]
@shinrariel-beichi He can't modify the source code, why he can't send some pull request! LOL

**Comment by shinrariel-beichi** [comment]
> @shinrariel-beichi He can't modify the source code, why he can't send some pull request! LOL

I'll taught her until she knows this.

**Comment by riflowth** [comment]
@shinrariel-beichi You can send a pull request for this feature *(SALTED2MD5 encryption)*
