### ISSUE TITLE
Custom MySQL table name

### ISSUE THREAD

**Issue by JeansouLiu** [riflowth/SkinSystem#86]
I am using Authme and Blessing skin server(https://github.com/bs-community/blessing-skin-server)
And the passwordHash is BCRYPT
But it seems that SkinSystem doesn't support it.
Is there any way to change skinsystem's passwordhash?

**Comment by riflowth** [comment]
https://github.com/riflowth/SkinSystem/blob/master/resources/server/authenCore.php#L10-L17
SkinSystem is support BCRYPT

**Comment by JeansouLiu** [comment]
> https://github.com/riflowth/SkinSystem/blob/master/resources/server/authenCore.php#L10-L17
> SkinSystem is supported BCRYPT

`    # Table of the database
    mySQLTablename: users
    # Column of IDs to sort data
    mySQLColumnId: uid`
Maybe it doesn't support custom table name

**Comment by JeansouLiu** [comment]
> > https://github.com/riflowth/SkinSystem/blob/master/resources/server/authenCore.php#L10-L17
> > SkinSystem is supported BCRYPT
> 
> ` # Table of the database mySQLTablename: users # Column of IDs to sort data mySQLColumnId: uid`
> Maybe it doesn't support custom table name

![image](https://user-images.githubusercontent.com/47891648/80301242-848f7780-87d5-11ea-8282-373cf462b78b.png)

**Comment by riflowth** [comment]
You can config table name on **config.nogit.php**

**Comment by JeansouLiu** [comment]
> You can config table name on **config.nogit.php**

But I haven't found any option to change the table name
https://github.com/riflowth/SkinSystem/wiki/Configuration

**Comment by JeansouLiu** [comment]
> You can config table name on **config.nogit.php**

It only has a option to edit database name
but no option to change table name

**Comment by riflowth** [comment]
Use the latest version

**Comment by JeansouLiu** [comment]
> Use the latest version (Master branch)

But column still can't set
`    # Column of IDs to sort data
    mySQLColumnId: uid`

**Comment by riflowth** [comment]
https://github.com/riflowth/SkinSystem/blob/master/config.nogit.php.example

**Comment by JeansouLiu** [comment]
> https://github.com/riflowth/SkinSystem/blob/master/config.nogit.php.example

`'am' => [
    'enabled' => false,
    'host' => '',
    'port' => '',
    'database' => '',
    'username' => '',
    'password' => '',
    'table' => 'authme',
    'hash' => [
      'method' => 'sha256'
    ],
    'authsec' => [
      'enabled' => false,
      'failed_attempts' => 3,
      'threshold_hours' => 24
    ]
  ],`
It seems that it can only change the table name
But what I need is to change the *column* name
The default id column of Authme is id
and I changed it to uid
Before I changing it, it was working fine
reinstalling isn't work

**Comment by riflowth** [comment]
Why did you need to change the column name?
(Solution, edit the source code: https://github.com/riflowth/SkinSystem/blob/master/resources/server/authenCore.php)
