### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by ghost** [riflowth/SkinSystem#89]
Hello, I have downloaded the latest version source code in .zip and set up the database for authme and Skinsrestorer, when I open the page it says: HTTP ERROR 500
https://projectmod.cz/skin
what should I do?

Thanks

**Comment by ITZVGcGPmO** [comment]
You've had a server misconfiguration or have not installed all the required libraries..

![](https://http.cat/500.jpg)

**Comment by averyanalex** [comment]
chown -R www-data:www-data /var/www/skin
helped me on Ubuntu 20.04 with Apache2
