### ISSUE TITLE
[Feature Request] skinRender.php | HEAD | 2D

### ISSUE THREAD

**Issue by totoberg123** [riflowth/SkinSystem#90]
Hello!

The skinRender.php file is great!

Only thing I would like to see is the option to give a 2D head as output ([front view like this](https://crafatar.com/avatars/853c80ef3c3749fdaa49938b674adae6)) .

I wont be able to create this feature myself, so I hope you guys can add it.

Thanks.

**Comment by riflowth** [comment]
#79

**Comment by ITZVGcGPmO** [comment]
a user by the name of Anonimo in [our discord](https://skinsrestorer.net/discord) posted [how they did this](https://discord.com/channels/186794372468178944/474606828924436481/728114358999056475) by using the skinRender URL of `yourwebsite.net/skinsystem_folder/resources/server/skinRender.php?headOnly=true&vr=0&hr=0&user={username}`
