### ISSUE TITLE
Error on login with Wordpress hash

### ISSUE THREAD

**Issue by FabioZumbi12** [riflowth/SkinSystem#93]
<s>I having this error on try to upload a skin without authme auth:
```
Uncaught ReferenceError: Swal is not defined
    at Object.<anonymous> (skinCore.js:21)
    at u (jquery_3.3.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery_3.3.1.min.js:2)
    at k (jquery_3.3.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery_3.3.1.min.js:2)
```
Using the master version updated on 23 Apr, not form releases</s>
Fixed by replace to `https://cdn.jsdelivr.net/npm/sweetalert2@9.15.3/dist/sweetalert2.all.min.js` on index.php

Edit: A question. Using with authme login, it wont support `wordpress` hash method? I getting this error:
![image](https://user-images.githubusercontent.com/5833818/87179458-242cb400-c2b5-11ea-87d1-633abda353e0.png)
It seems caused by the same Swal error. The source:
![image](https://user-images.githubusercontent.com/5833818/87179927-f09e5980-c2b5-11ea-88e0-fe9f8ad0d013.png)

**Comment by riflowth** [comment]
@FabioZumbi12 *Sorry for late reply.*
 You should check and show us your **error log** of **authenCore.php**
