### ISSUE TITLE
Kill nginx

### ISSUE THREAD

**Issue by Shaytir** [riflowth/SkinSystem#98]
Good day! I put the system on my site, it works great, but over time I found a certain * bug * (?), The point is that if you put layered skins (more than 2 layers), then it thinks for a very long time and only then changes it. (This plugin will be used by players) Thanks to this bug, you can put a web server (nginx).

**Comment by riflowth** [comment]
Could you give more information please? *(I want some error log)*

**Comment by sanyadovbnya** [comment]
I have the same problem, could you fix it or at least tell me which direction to look for?

**Comment by aljaxus** [comment]
> I have the same problem, could you fix it or at least tell me which direction to look for?
> @sanyadovbnya 

You should really look for "l o g s", filter private information (such as public addresses of your clients) out of it and publish it here for review.

**Comment by sanyadovbnya** [comment]
> > I have the same problem, could you fix it or at least tell me which direction to look for?
> > @sanyadovbnya
> 
> You should really look for "l o g s", filter private information (such as public addresses of your clients) out and publish them here for review. The most important one is the `error.log` file, but it wouldn't hurt if we had the `access.log` too.

I have no errors in "l o g s", The plugin thinks it works the way it should. Do you have a sample site where this plugin is installed so I can see how it works there? Perhaps the problem is really on my side. Thank you.
