### ISSUE TITLE
Simple Question

### ISSUE THREAD

**Issue by Link0Darck** [riflowth/SkinSystem#99]
Hello,
Is it possible that you add a category that allows you to download the skins from the database like this
https://minecraft.tools/fr/skin.php

**Comment by riflowth** [comment]
You just pick a skin from other website to upload to the **Skinsystem**

**Comment by Link0Darck** [comment]
I give the site to know of what I speak because I would like to be able with the site of skinrestorer because one can upload but one cannot recover a skin of the base to give of skin restorer and its would be well

**Comment by ITZVGcGPmO** [comment]
https://github.com/riflowth/SkinSystem/blob/master/resources/server/skinRender.php
